BugTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('web.urls')),
]

web/urls.py
#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
from django.urls import path, re_path, include
from web.views import account
from web.views import project
from web.views import wiki
from web.views import file
from web.views import setting
from web.views import issues
from web.views import dashboard
from web.views import statistics

urlpatterns = [
    path('register/', account.register, name='register'),
    path('send_sms/', account.send_sms, name='send_sms'),
    path('login/', account.login, name='login'),
    path('login/sms/', account.login_sms, name='login_sms'),
    path('image/code/', account.image_code, name='image_code'),
    path('', account.index, name='index'),
    path('logout/', account.logout, name='logout'),

    path('project/list', project.project_list, name='project_list'),
    re_path(r'project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/', project.project_star, name='project_star'),
    re_path(r'project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/', project.project_unstar,
            name='project_unstar'),
    # 项目管理
    re_path(r'manage/(?P<project_id>\d+)/', include([
        path('dashboard/', dashboard.dashboard, name='dashboard'),
        path('dashboard/issues/chart', dashboard.issues_chart, name='issues_chart'),
        path('statistics/', statistics.statistics, name='statistics'),
        path('statistics/priority', statistics.priority, name='statistics_priority'),
        path('statistics/project_user', statistics.project_user, name='statistics_project_user'),
        path('file/', file.file, name='file'),
        path('file/delete/', file.file_delete, name='file_delete'),
        path('file/post/', file.file_post, name='file_post'),
        re_path(r'file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),
        path('cos/credential/', file.cos_credential, name='cos_credential'),

        path('wiki/', wiki.wiki, name='wiki'),
        path('wiki/add/', wiki.wiki_add, name='wiki_add'),
        re_path(r'wiki/delete/(?P<wiki_id>\d+)/', wiki.wiki_delete, name='wiki_delete'),
        re_path(r'wiki/edit/(?P<wiki_id>\d+)/', wiki.wiki_edit, name='wiki_edit'),
        re_path(r'wiki/upload/', wiki.wiki_upload, name='wiki_upload'),
        path('wiki/catalog/', wiki.wiki_catalog, name='wiki_catalog'),

        path('setting/', setting.setting, name='setting'),
        path('setting/delete/', setting.delete, name='setting_delete'),

        path('issue/', issues.issue, name='issue'),
        re_path(r'issue/detail/(?P<issue_id>\d+)/', issues.issue_detail, name='issue_detail'),
        re_path(r'issue/replies/(?P<issue_id>\d+)/', issues.issue_replies, name='issue_replies'),
        re_path(r'issue/change/(?P<issue_id>\d+)/', issues.issue_change, name='issue_change'),
        path('issue/invite/url/', issues.invite_url, name='invite_url'),
    ], None)),
    re_path(r'invite/join/(?P<code>\w+)', issues.invite_join, name='invite_join'),
]

web/models.py
from django.db import models


class UserInfo(models.Model):
    """用户表"""
    username = models.CharField(verbose_name='用户名', max_length=32)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=11)
    password = models.CharField(verbose_name='密码', max_length=32)

    def __str__(self):
        return self.username


class PricePolicy(models.Model):
    """价格策略"""
    category_choices = (
        (1, "免费版"),
        (2, "收费版"),
        (3, "其他"),
    )

    category = models.SmallIntegerField(verbose_name="收费类型", choices=category_choices, default=1)
    title = models.CharField(verbose_name="标题", max_length=32)
    price = models.PositiveIntegerField(verbose_name="价格")
    project_num = models.PositiveIntegerField(verbose_name="项目数")
    project_member = models.PositiveIntegerField(verbose_name="项目成员数")
    project_space = models.PositiveIntegerField(verbose_name="单项目空间(G)")
    per_file_size = models.PositiveIntegerField(verbose_name="单文件大小(M)")
    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)


class Transaction(models.Model):
    """交易记录"""
    status_choices = (
        (1, "未支付"),
        (2, "已支付"),
    )

    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    order = models.CharField(verbose_name="订单号", max_length=64, unique=True)
    user = models.ForeignKey(verbose_name="用户", to="UserInfo", on_delete=models.DO_NOTHING)
    price_policy = models.ForeignKey(verbose_name="价格策略", to="PricePolicy", on_delete=models.DO_NOTHING)
    count = models.IntegerField(verbose_name="数量(年)", help_text="0表示无限期")
    price = models.IntegerField(verbose_name="实际支付价格")
    start_datetime = models.DateTimeField(verbose_name="开始时间", null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name="结束时间", null=True, blank=True)
    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)


class Project(models.Model):
    """项目表"""
    color_choices = (
        (1, "#56b8eb"),
        (2, "#f28033"),
        (3, "#ebc656"),
        (4, "#a2d148"),
        (5, "#20bfa4"),
        (6, "#7461c2"),
        (7, "#20bfa3"),
    )

    name = models.CharField(verbose_name="项目名称", max_length=32)
    color = models.SmallIntegerField(verbose_name="颜色", choices=color_choices, default=1)
    desc = models.CharField(verbose_name="描述", max_length=255, null=True, blank=True)
    use_space = models.IntegerField(verbose_name="已使用空间", default=0)
    star = models.BooleanField(verbose_name="星标", default=False)
    join_count = models.SmallIntegerField(verbose_name="参与人数", default=1)
    creator = models.ForeignKey(verbose_name="创建者", to="UserInfo", on_delete=models.DO_NOTHING)
    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    bucket = models.CharField(verbose_name="COS桶", max_length=128)
    # 便于查询，但无法完成增加，删除，修改操作，此外through_fields字段顺序要与ProjectUser保持一致
    # project_user = models.ManyToManyField(to="UserInfo", through="ProjectUser", through_fields=("project", "user"))


class ProjectUser(models.Model):
    """项目参与者"""
    user = models.ForeignKey(verbose_name="用户", to="UserInfo", on_delete=models.DO_NOTHING)
    project = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.DO_NOTHING)
    star = models.BooleanField(verbose_name="星标", default=False)
    create_datetime = models.DateTimeField(verbose_name="加入时间", auto_now_add=True)


class Wiki(models.Model):
    """Wiki"""
    title = models.CharField(verbose_name="标题", max_length=255, default='')
    content = models.TextField(verbose_name="内容")
    project = models.ForeignKey(to="Project", verbose_name="项目", on_delete=models.SET_NULL, null=True, blank=True)
    parent = models.ForeignKey(verbose_name="父文档", to="self", null=True, blank=True, on_delete=models.SET_NULL,
                               related_name="children")

    depth = models.IntegerField(verbose_name="深度", default=1)

    def __str__(self):
        return self.title


class FileRepository(models.Model):
    """文件库"""
    project = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.CASCADE)
    file_type_choices = (
        (1, "文件"),
        (2, "目录"),
    )
    file_type = models.SmallIntegerField(verbose_name="类型", choices=file_type_choices)
    name = models.CharField(verbose_name="名称", max_length=128, help_text="文件/目录名")
    key = models.CharField(verbose_name="存在在COS中KEY", max_length=128, null=True, blank=True)
    file_size = models.BigIntegerField(verbose_name="文件大小", null=True, blank=True, help_text="字节")
    file_path = models.CharField(verbose_name="文件路径", max_length=255, null=True, blank=True)
    parent = models.ForeignKey(verbose_name="父目录", to="self", related_name="children", blank=True, null=True,
                               on_delete=models.CASCADE)
    update_user = models.ForeignKey(verbose_name="最近更新者", to="UserInfo", on_delete=models.SET_NULL, null=True)
    update_datetime = models.DateTimeField(verbose_name="更新时间", auto_now=True)


class Issues(models.Model):
    """ 问题 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.DO_NOTHING)
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssueType', on_delete=models.DO_NOTHING)
    module = models.ForeignKey(verbose_name='模块', to='Module', null=True, blank=True, on_delete=models.DO_NOTHING)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = (
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='UserInfo', related_name='task', null=True, blank=True,
                               on_delete=models.DO_NOTHING)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems',
                                on_delete=models.DO_NOTHING)

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """issue模块"""
    project = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.DO_NOTHING)
    title = models.CharField(verbose_name="模块名称", max_length=32)

    def __str__(self):
        return self.title


class IssueType(models.Model):
    ISSUE_TYPE_INIT_LIST = ["任务", "功能", "Bug"]

    title = models.CharField(verbose_name="类型名称", max_length=32)
    project = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.title


class IssueReply(models.Model):
    """问题回复"""

    reply_type_choices = (
        (1, "修改记录"),
        (2, "回复"),
    )
    reply_type = models.IntegerField(verbose_name="类型", choices=reply_type_choices)
    issues = models.ForeignKey(verbose_name="问题", to="Issues", on_delete=models.CASCADE)
    content = models.TextField(verbose_name="描述")
    creator = models.ForeignKey(verbose_name="创建者", to="UserInfo", related_name="create_reploy", on_delete=models.DO_NOTHING)
    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    reply = models.ForeignKey(verbose_name="回复", to="self", null=True, blank=True, on_delete=models.CASCADE)


class ProjectInvite(models.Model):
    """ 项目邀请码 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='空表示无数量限制')
    used_count = models.PositiveIntegerField(verbose_name='已邀请数量', default=0)
    period_choices = (
        (30, '30分钟'),
        (60, '1小时'),
        (300, '5小时'),
        (1440, '24小时'),
    )
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_invite', on_delete=models.CASCADE)

web/forms/wiki.py
#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
# filename: wiki.py

from django import forms
from django.db.models import Q
from web import models
from web.forms.bootstrap import BootStrapForm


class WikiModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.Wiki
        fields = ["title", "content", "parent"]
        # exclude = ["project"]

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        choice_list = [("", "请选择"), ]
        wiki_obj = models.Wiki.objects.filter(
            Q(project=self.request.tracker.project) & ~Q(id=self.instance.id)).values_list("id", "title")
        choice_list.extend(wiki_obj)
        self.fields["parent"].choices = choice_list

web/views.py
from django import forms
from django.core.validators import RegexValidator
from django.shortcuts import render
from web import models


class RegisterModelForm(forms.ModelForm):
    mobile_phone = forms.CharField(label='手机号', validators=[RegexValidator(r'^(1[3|4|5|6|7|8|9])\d{9}$', '手机号格式错误'), ])
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput())

    confirm_password = forms.CharField(
        label='重复密码',
        widget=forms.PasswordInput())
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput())

    class Meta:
        model = models.UserInfo
        fields = ['username', 'email', 'password', 'confirm_password', 'mobile_phone', 'code']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['placeholder'] = '请输入%s' % (field.label,)


def register(request):
    form = RegisterModelForm()
    return render(request, 'register.html', {'form': form})

web/views/dashboard.py
#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
from django.http import JsonResponse
from django.shortcuts import render
from web import models
from django.db.models import Count
import collections
import datetime
import time


def dashboard(request, project_id):
    """概览"""
    status_dict = collections.OrderedDict()
    for key, value in models.Issues.status_choices:
        status_dict[key] = {"text": value, "count": 0}
    issues_data = models.Issues.objects.filter(project_id=project_id).values("status").annotate(count=Count("id"))
    for item in issues_data:
        status_dict[item["status"]]["count"] = item["count"]

    # 项目成员
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values("user_id", "user__username")

    # 最近的10个问题
    top_ten = models.Issues.objects.filter(project_id=project_id, assign_id__isnull=False).order_by("-id")[0:10]

    context = {
        "status_dict": status_dict,
        "user_list": user_list,
        "top_ten": top_ten,
    }
    return render(request, "dashboard.html", context)


def issues_chart(request, project_id):
    """在概览中生成highchart所需的数据"""
    # 最近30天每天创建的问题数量
    today = datetime.datetime.now().date()
    date_dict = collections.OrderedDict()
    for i in range(0, 30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple()) * 1000, 0]

    result = models.Issues.objects.filter(project_id=project_id,
                                          create_datetime__gte=today - datetime.timedelta(days=30)).extra(
        select={"ctime": "DATE_FORMAT(web_issues.create_datetime, '%%Y-%%m-%%d')"}).values('ctime').annotate(
        ct=Count('id'))  # <QuerySet [{'ctime': '2022-04-10', 'ct': 1}, {'ctime': '2022-04-17', 'ct': 2}]>
    for item in result:
        date_dict[item["ctime"]][1] = item["ct"]

    return JsonResponse({"status": True, "data": list(date_dict.values())})

web/views/setting.py
from django.shortcuts import render, redirect
from web.utils.tencent import cos
from web import models
def setting(request, project_id):
    return render(request, 'setting.html')


def delete(request, project_id):
    if request.method == "GET":
        return render(request, 'setting_delete.html')

    project_name = request.POST.get("project_name")
    # 判断项目名是否合法
    if not project_name or project_name != request.tracker.project.name:
        return render(request, "setting_delete.html", {"error": "项目名错误"})

    # 只有创建者可以删除
    if request.tracker.user != request.tracker.project.creator:
        return render(request, "setting_delete.html", {"error": "需要创建者删除"})
    # 删除COS桶
    cos.delete_bucket(request.tracker.project.bucket)
    models.Project.objects.filter(id=project_id).delete()
    # 删除项目
    return redirect("project_list")

web/templates/index.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}
首页
{% endblock %}
{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
{% endblock %}
{% block content %}
<div>
    <img src="{% static 'img/index/index-1.png' %}" alt="">
    <img src="{% static 'img/index/index-2.png' %}" alt="">
    <img src="{% static 'img/index/index-3.png' %}" alt="">
    <img src="{% static 'img/index/index-4.png' %}" alt="">
</div>
{% endblock %}

web/templates/invite_join.html
{% extends 'layout/manage.html' %}

{% block title %}加入项目{% endblock %}

{% block css %}
    <style>
        .no-radius {
            border-radius: 0;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        {% if error %}
            <div class="alert alert-danger no-radius">
                <h4><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ error }}</h4>
            </div>
        {% else %}
            <div class="alert alert-success no-radius">
                <h4><i class="fa fa-check-circle" aria-hidden="true"></i> 加入成功 </h4>
                <a href="{% url 'dashboard' project_id=project.id %}">点击跳转至项目</a>
            </div>
        {% endif %}

    </div>

{% endblock %}

web/templates/login_sms.html
{% extends 'layout/base.html' %}
{% load static %}
{% block title %}BugTracker|登录{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}
{% block content %}
    <div class="account">
        <div class="title">用户登录</div>
        <form action="" id="login_sms_form" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input type="button" id="smsBtn" class="btn btn-default" value="获取验证码">
                            </div>
                        </div>
                    </div>

                {% else %}
                    <div class="form-group">
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="row">
                <div class="col-xs-12">
                    <input type="button" id="submitBtn" class="btn btn-primary col-xs-3" value="登 录">
                    <a href="{% url 'login' %}" style="float: right">用户名登录?</a>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            ClickSMSBtn();
            ClickSubmitBtn();
        });

        // 通过ajax提交form表单中的数据
        function ClickSubmitBtn() {
            $('#submitBtn').click(function () {
                $('.error-msg').empty();
                $.ajax({
                    url: "{% url 'login_sms' %}",
                    type: "POST",
                    dataType: "JSON",
                    // 收集表单中的数据
                    data: $("#login_sms_form").serialize(), // 包含表单所有字段的数据，并且携带了csrf token
                    success: function (res) {
                        if (res.status) {
                            location.href = res.url  // 跳转到登录页面
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        function sendSMSRemind() {
            // 倒计时
            let $BtnSMS = $('#smsBtn');
            $BtnSMS.prop("disabled", true);
            let time = 60;
            let remind = setInterval(function () {
                $BtnSMS.val(time + "秒后重新发送")
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind)
                    $BtnSMS.val("点击获取验证码").prop("disabled", false)
                }
            }, 1000)
        }

        /*获取验证码的事件*/
        function ClickSMSBtn() {
            $('#smsBtn').click(function () {
                $(".error-msg").empty() // 清空现有的错误信息
                // 获取用户输入的手机号
                let mobilePhone = $('#id_mobile_phone').val()
                // 发送ajax请求
                $.ajax({
                    url: "{% url 'send_sms' %}",
                    type: "POST",
                    data: {"mobile_phone": mobilePhone, template: "login"},
                    dataType: "JSON", // 将服务器返回的数据反序列化为字典
                    success: function (res) { // res: 后端返回的值
                        if (res.status) {
                            sendSMSRemind();
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

web/templates/project_list.html
{% extends 'layout/manage.html' %}
{% block css %}
    <style>
        .project {
            margin-top: 10px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;

        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;

            display: flex;
            justify-content: space-between;

            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid project">
        <div style="margin: 10px 0;">
            <a class="btn btn-primary" data-toggle="modal" data-target="#addProjectModel"> <i
                    class="fa fa-plus-circle" aria-hidden="true"></i> 新建项目
            </a>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-star"></i> 我关注的</h3>
            </div>
            <div class="panel-body">
                {% for item in projects.star %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}
                        </a>

                        <div class="info">
                            <div>
                                <a href="{% url 'project_unstar' project_type=item.type project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-list"></i> 我创建的</h3>
            </div>
            <div class="panel-body">
                {% for item in projects.mine %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}
                        </a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='mine' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-share-alt-square"></i> 我参与的</h3>
            </div>
            <div class="panel-body">
                {% for item in projects.join %}
                    <div class="item">
                        <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.get_color_display }}
                        </a>

                        <div class="info">
                            <div>
                                <a href="{% url 'project_star' project_type='join' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="modal fade" id="addProjectModel" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">新建项目</h4>
                </div>
                <div class="modal-body">
                    <form id="addProject">
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="btnSubmit">保存</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

{% block js %}
    <script>
        $(function () {
            ClickSubmitBtn();
        });

        function ClickSubmitBtn() {
            $('#btnSubmit').click(function () {
                $('#error-msg').empty();
                $.ajax({
                    url: "{% url 'project_list' %}",
                    type: "POST",
                    data: $('#addProject').serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.reload()  // 刷新页面
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}